version: '3'
services:
  database:
    image: "postgres:12.4"
    restart: always
    container_name: df_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=defrag
      - POSTGRES_DB=Defrag
    volumes:
      - ./df_data:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
    container_name: df_bot
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=defrag
      - POSTGRES_DB=Defrag
      - POSTGRES_ADDRESS=df_database
      - CLIENT_TOKEN=${CLIENT_TOKEN}
      - DFBOT_ENVIRONMENT=CONTAINER
      - PYTHONPATH=.:/usr/local/lib/python
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY={AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-west-2
    volumes:
      - src:/src

volumes:
  db:
  src:
  pgadata:

