version: '3'
services:
  database:
    image: "postgres:12.4"
    restart: always
    container_name: df_database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=defrag
      - POSTGRES_DB=Defrag
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./data:/data
    ports:
      - "5432:5432"

  bot:
    build:
      context: ./src
      dockerfile: Dockerfile
    restart: always
    container_name: df_bot
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=defrag
      - POSTGRES_DB=Defrag
      - POSTGRES_ADDRESS=df_database
      - CLIENT_TOKEN=${CLIENT_TOKEN}
      - DFBOT_ENVIRONMENT=CONTAINER
      - PYTHONPATH=.:/usr/local/lib/python
<<<<<<< HEAD
      - AWS_ACCESS_KEY_ID=AKIA4OOITDEZZEIUL4XV
      - AWS_SECRET_ACCESS_KEY=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
      - AWS_DEFAULT_REGION="us-west-2"
=======
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY={AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=us-west-2
>>>>>>> 791b55951da445bf2b9c22dcb1b7c5992a7ee350
    volumes:
      - src:/src

volumes:
  db:
  src:
  pgadata:

